version: "2.15.1" #We specify a version for Compose. Make sure Compose is compatible with Docker
services:
  client: #Define the client service so we can run it in an isolated environment.
    stdin_open: true
    build:
      context: .
      # The client service requires a docker file to be specified.
      # For development, we’re going to use the Dockerfile.dev file.
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
# TODO: Set up prod deployment too ?
